export type DeckItem = { quantity: number; card_name: string };

export type DeckRecord = {
  id: number;
  name: string;
  source: string;
  archetype_guess: string;
  mainboard: DeckItem[];
  sideboard: DeckItem[];
};

export type CardView = {
  id: string;
  name: string;
  was_foretold?: boolean;
  foretell_order?: number | null;
  foretold_turn?: number | null;
  mana_cost?: string;
  oracle_text?: string;
  type_line?: string;
  base_type_line?: string;
  image_uri?: string;
  card_faces?: {
    name?: string;
    mana_cost?: string;
    oracle_text?: string;
    type_line?: string;
    image_uri?: string;
  }[];
  layout?: string;
  tapped: boolean;
  summoning_sick: boolean;
  power: number | null;
  toughness: number | null;
  base_power?: number | null;
  base_toughness?: number | null;
  printed_power?: string | null;
  printed_toughness?: string | null;
  keywords?: string[];
  keyword_counts?: Record<string, number>;
  colors?: string[];
  mana_source_colors?: string[];
  mana_source_amounts?: Record<string, number>;
  counters?: Record<string, number>;
  damage_marked?: number;
  selected_face_index?: number | null;
  loyalty?: number | null;
  types: string[];
  is_token?: boolean;
  attached_to?: string | null;
  bestowed?: boolean;
  effect_warnings?: string[];
};

export type PlayerView = {
  id: number;
  name: string;
  life: number;
  counters?: Record<string, number>;
  library_count: number;
  hand_count: number;
  battlefield: CardView[];
  hand: CardView[];
  graveyard: CardView[];
  graveyard_count: number;
  exile: CardView[];
  exile_count: number;
  mana_pool: Record<string, number>;
  snow_mana_pool?: Record<string, number>;
  restricted_mana_pool?: {
    color: string;
    amount: number;
    snow: boolean;
    rule: { cast_types?: string[]; activate_types?: string[]; unsupported?: boolean };
  }[];
};

export type MatchState = {
  id: string;
  revision?: number;
  discards_this_turn?: Record<string, number>;
  mode?: "player_vs_ai" | "ai_vs_ai" | "human_vs_human";
  controllers?: Record<string, "human" | "ai">;
  turn: number;
  active_player: number;
  priority_player: number;
  step: string;
  combat_damage_stage?: "none" | "first" | "regular";
  winner: number | null;
  score: Record<string, number>;
  pregame_pending?: boolean;
  mulligan_count?: Record<string, number>;
  mulligan_bottomed?: Record<string, number>;
  kept_hands?: number[];
  priority_stops?: Record<string, string[]>;
  players: Record<string, PlayerView>;
  stack: { id: string; label: string; controller: number; effect_key: string }[];
  attackers?: string[];
  attack_targets?: Record<string, string>;
  attack_bands?: string[][];
  blocks?: Record<string, string[]>;
  game_number?: number;
  root_seed?: number | null;
  game_seed?: number | null;
  next_play_draw_chooser?: number | null;
  best_of?: number;
  games_needed?: number;
  match_complete?: boolean;
  day_night?: "none" | "day" | "night";
  sideboard_sizes?: Record<string, number>;
  sideboarding?: Record<string, { mainboard: DeckItem[]; sideboard: DeckItem[]; applied: boolean }>;
  log: string[];
  pending_mechanic_choice?: {
    kind: "effect_cast" | "scry" | "scry_top_order" | "surveil" | "surveil_top_order" | "proliferate" | "ward_payment" | "ward_cost_cards" | "counter_payment" | "optional_search" | "graveyard_return" | "discard" | "each_player_discard" | "cleanup_discard" | "mulligan_bottom" | "opening_hand" | "opening_hand_exile" | "sacrifice" | "draw" | "land_entry" | "saga_entry" | "attacking_token_target" | "topdeck_reveal_creature" | "topdeck_put" | "topdeck_bottom_order" | "look_top_choose" | "look_top_select_hand" | "search_library" | "combat_damage" | "copy_target";
    player_id: number;
    options?: string[];
    count?: number;
    min_count?: number;
    label?: string;
    source_id?: string;
    source_name?: string;
    stage?: "first" | "regular";
    can_restart?: boolean;
    target_slot_number?: number;
  } | null;
  pending_replacement_choice?: {
    event: string;
    player_id: number;
    options: { source_id: string; name: string; controller: number; static_order: number }[];
  } | null;
  pending_trigger_order?: {
    phase?: "targets" | "optional";
    event: string;
    current_controller: number;
    groups?: Record<string, { _choice_id: string; source_card_id: string; label: string }[]>;
    current_stack_id?: string;
  } | null;
};

export type LegalMove = {
  outputs?: Record<string, number>;
  cost_text?: string;
  cast_variant?: 'bestow';
  selected_face_index?: number;
  kind?: "effect_cast" | "scry" | "scry_top_order" | "surveil" | "surveil_top_order" | "proliferate" | "ward_payment" | "ward_cost_cards" | "counter_payment" | "optional_search" | "graveyard_return" | "discard" | "each_player_discard" | "cleanup_discard" | "mulligan_bottom" | "opening_hand" | "opening_hand_exile" | "sacrifice" | "draw" | "land_entry" | "saga_entry" | "attacking_token_target" | "topdeck_reveal_creature" | "topdeck_put" | "topdeck_bottom_order" | "look_top_choose" | "look_top_select_hand" | "search_library" | "combat_damage" | "copy_target";
  entry_choice?: "tapped" | "pay_two_life";
  player_id?: number;
  count?: number;
  min_count?: number;
  label?: string;
  source_id?: string;
  source_name?: string;
  stage?: "first" | "regular";
  can_restart?: boolean;
  target_slot_number?: number;
  option_labels?: Record<string, string>;
  option_type_lines?: Record<string, string>;
  type: string;
  card_id?: string;
  card_view?: CardView;
  from_exile?: boolean;
  from_library?: boolean;
  from_graveyard?: boolean;
  return_card_id?: string;
  crew_value?: number;
  crew_candidates?: { id: string; name: string; power: number }[];
  card_name?: string;
  mana_cost?: string;
  hybrid_symbols?: { symbol: string; choices: string[] }[];
  attack_costs?: Record<string, Record<string, {
    mana_cost: string;
    hybrid_symbols: { symbol: string; choices: string[] }[];
  }>>;
  block_costs?: Record<string, { mana_cost: string; hybrid_symbols: { symbol: string; choices: string[] }[] }>;
  x_value?: number;
  cost_options?: {
    id: string;
    additional_cost_group?: string | null;
    kicked?: boolean;
    kicker_base_id?: string | null;
    target_hints?: LegalMove['target_hints'];
    label: string;
    mana_cost: string;
    hybrid_symbols?: { symbol: string; choices: string[] }[];
    pay_life: number;
    pay_life_x?: boolean;
    discard_cards: number;
    discard_x?: boolean;
    discard_all?: boolean;
    sacrifice_all?: boolean;
    sacrifice_creatures: number;
    sacrifice_kind?: string;
    discard_card_ids?: string[];
    sacrifice_card_ids?: string[];
  }[];
  options?: string[];
  attackers?: { id: string; name: string }[];
  defenders?: { id: string; label: string; kind: string }[];
  blockers?: { id: string; name: string }[];
  targets?: { id: string; name: string }[];
  ability_index?: number;
  ability_label?: string;
  ability_delta?: number;
  reason?: string;
  event?: string;
  replacement_source_id?: string;
  replacement_name?: string;
  trigger_order?: string[];
  trigger_labels?: string[];
  stack_id?: string;
  target_card_id?: string;
  target_player?: number;
  target_name?: string;
  accept?: boolean;
  target_hints?: {
    single_target_alternative?: boolean;
    choice_schema?: Record<string, unknown>;
    player_targets?: { id: number; name: string }[];
    creature_targets?: { id: string; name: string }[];
    permanent_targets?: { id: string; name: string }[];
    graveyard_card_targets?: { id: string; name: string }[];
    graveyard_creature_targets?: { id: string; name: string }[];
    graveyard_permanent_targets?: { id: string; name: string }[];
    land_targets?: { id: string; name: string }[];
    artifact_targets?: { id: string; name: string }[];
    enchantment_targets?: { id: string; name: string }[];
    noncreature_permanent_targets?: { id: string; name: string }[];
    aura_targets?: { id: string; name: string }[];
    aura_cost_options?: Record<string, string[]>;
    planeswalker_targets?: { id: string; name: string }[];
    stack_targets?: { id: string; label: string }[];
    face_names?: string[];
    modes?: string[];
    available_modes?: string[];
    choose_two_modes?: boolean;
    mode_target_hints?: Record<string, {
      player_targets?: { id: number; name: string }[];
      creature_targets?: { id: string; name: string }[];
      planeswalker_targets?: { id: string; name: string }[];
      permanent_targets?: { id: string; name: string }[];
      artifact_targets?: { id: string; name: string }[];
      enchantment_targets?: { id: string; name: string }[];
      land_targets?: { id: string; name: string }[];
      graveyard_card_targets?: { id: string; name: string }[];
      graveyard_creature_targets?: { id: string; name: string }[];
      graveyard_permanent_targets?: { id: string; name: string }[];
      stack_targets?: { id: string; label: string }[];
    }>;
    requires_x_value?: boolean;
    x_value_max?: number;
    up_to_target_count?: number;
    required_distinct_target_count?: number;
    ordered_counter_amounts?: number[];
    ordered_counter_type?: string;
    supports_divide?: boolean;
    divide_max_targets?: number;
    library_search?: {
      contains?: string;
      destination?: string;
      max_count?: number;
      allow_zero?: boolean;
      candidates?: { id: string; name: string }[];
    };
  };
};
